apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
  namespace: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
